### ISSUE TITLE
Document what game compatibility levels mean

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-web#104]
As indicated in [this comment](https://github.com/scummvm/scummvm-web/pull/102#issuecomment-536321517), there is confusion about what different levels of game compatibility mean. 

> > Historically 'excellent' was reserved to the games we had access to the
 original sources for. But now I see that bunch of SCI games were put to
 that category which is kind of misleading.
> 
> I thought that standard was broken long ago, though. Or did we receive
the source code for Toonstruck? It's listed as "Excellent", but last
time I checked it had graphical glitches. (The ones I saw when I played
through the early parts a couple of years ago were #6867 and #6869. The
first one of them can be easily reproduced since it happens in the very
first room of the game.)

It would be good to document whatever outcome we decide, either on this GitHub repo as a Wiki, in the site Readme, or somewhere else.

**Comment by Mataniko** [comment]
These make sense to me and are pretty intuitive:
Excellent: No known (major) issues.
Good: Minor issues that do not impact the experience. Games can be played all the way through.
Bugged: Game runs, but may crash or major graphical/audio glitches. May not be able to be played all the way through.
Broken: Game may not start or have severe issues rendering it unplayable.
Untested: Pretty straight forward

@sev- ?

**Comment by sev-** [comment]
@Mataniko the list you provided makes sense to me, please go ahead

**Comment by Thunderforge** [comment]
Alternatively, #121 proposes we get rid of compatibility levels entirely and only show versions that are supported in a particular release. That said, I'm okay with these descriptions so long as the current system is still in place.
