### ISSUE TITLE
Touché rendered as TouchÃ© on Compatibility page

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-web#112]
The game *Touché: The Adventures of the Fifth Musketeer* appears on the ScummVM [compatibility page](https://www.scummvm.org/compatibility/) as

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6200170/77276413-9aff5c00-6c88-11ea-8b1e-3c3166d62c22.png">

> TouchÃ©: The Adventures of the Fifth Musketeer

In other words, the `é` symbol is being improperly displayed as `Ã©`. In [data/compatibility/compat-DEV.xml](https://github.com/scummvm/scummvm-web/blob/045d25ed835ac79bade53d9d23bd6aff48899827/data/compatibility/compat-DEV.xml#L1725), it's listed correctly, so the issue must be with rendering.

Tested on macOS Safari and Firefox.

**Comment by lotharsm** [comment]
Yep, confirmed. Seems that the conversion to UTF8 fails here.
