### ISSUE TITLE
Full-sized screenshots are being displayed on the main page instead of compressed ones

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-web#120]
On the main page, the random screenshots gallery is currently showing the full-sized images (typically 80-200 KB) instead of the compressed images (typically 6-12 KB) that exist in `public_html/data/screenshots` folder. See for instance the HTML source from a recent page load:

```html
<section class="content gallery">
    <a href="/data/screenshots/westwood/bladerunner/bladerunner-win-fr-18-full.png" title="Blade Runner (Windows/French)">
        <img class="random-screenshot" src="/data/screenshots/westwood/bladerunner/bladerunner-win-fr-18-full.png" alt="Blade Runner (Windows/French)">
    </a>
</section>
```

The compressed versions should be displayed normally and the full one should only be loaded if the user clicks on it. This saves bandwidth and is a big help to those with low bandwidth (especially during the COVID-19 coronavirus!) or metered connections.

**Comment by lotharsm** [comment]
The problem here is that the resolution of the thumbnail .jpg files is smaller than the size of the random screenshot box, so in many cases, this would be a pretty significant downgrade quality-wise.

**Comment by Mataniko** [comment]
At one point you end up over optimizing for negligible results. The most important part of the site is the layout and content, which are highly optimized for low bandwidth ~1 second with 2G speeds and < 1 second in 3G speeds.

The entire main page is less than 20kb gzipped, followed by 200-300kb of images, with everything included the front page is probably smaller than 99% of websites out there.

The proper way to optimize image sizes on our site would be to recapture them at original resolution, no scaling filter and with aspect ratio correction and use browsers pixel-perfect scaling modes to display them at any size. Most ScummVM games are 320x200 (stretched to 320x240 with ARC) with limited amount of colors, these should not exceed more than 30 kb at that point.
