### ISSUE TITLE
ScummVm for Vita bug with Discworld 2

### ISSUE THREAD

**Issue by Anguawolf** [scummvm/scummvm-web#127]
- ScummVM version : **2.1.1**
    - Bug details, including instructions on reproducing: **Discworld 2. Start game, forward through intros and the "That's Death" song. The next scene should show camera pans down to wizards in the Great Hall with party favors and they reveal the plot of the game. What happens is the camera pans down, then it fades immediately to Act 1.**
    - Language of game (English, German, ...): **English**
    - Version of game (talkie, floppy, ...) **DOS, CD based and floppy**
    - Platform and Compiler (Win32, Linux, FreeBSD, ...): **PLAYSTATION VITA**
    - Attach a saved game if possible: NA
 
     IT ALSO SEEMS SOME SOUND CUES ARE MISSING.

**Comment by digitall** [comment]
This is the issue tracker for the ScummVM _website_, not the application.

If you want to report bugs in ScummVM, you should report these on the main bug tracker at https://bugs.scummvm.org

Closing as invalid.
