### ISSUE TITLE
ScummVM Vita Sound CUE issue with Discworld 2

### ISSUE THREAD

**Issue by Anguawolf** [scummvm/scummvm-web#128]
- ScummVM version : **2.1.1**
    - Bug details, including instructions on reproducing: **Discworld 2. Sounds appear not to be cued properly in Shades area. The characters are supposed to make their own signature comments and sounds at random. They are silent unless interacting**
    - Language of game (English, German, ...): **English**
    - Version of game (talkie, floppy, ...) **DOS, CD based and floppy**
    - Platform and Compiler (Win32, Linux, FreeBSD, ...): **PLAYSTATION VITA**
    - Attach a saved game if possible: NA

**Comment by digitall** [comment]
This is the issue tracker for the ScummVM website, not the application.

If you want to report bugs in ScummVM, you should report these on the main bug tracker at https://bugs.scummvm.org

Closing as invalid.
