### ISSUE TITLE
Delayed language switching

### ISSUE THREAD

**Issue by sev-** [scummvm/scummvm-web#33]
Due to the fact that we switch language via cookie, the cookie gets passed with one click delay.

Thus, our language switcher lags.

**Comment by rootfather** [comment]
But why does the language switcher works instantly on the main page, but not on the sub-pages?

**Comment by RichieSams** [comment]
Interesting... 
rootfather is correct http://scummvm.org/?lang=de works instantly
But http://scummvm.org/<anything>/?lang=de lags one page

**Comment by sev-** [comment]
I know, it also interferes with our RewriteRules.

**Comment by wjp** [comment]
From what I can tell, this is just a missing QSA in the rewrite rules, isn't it?

**Comment by sev-** [comment]
This has been fixed by wjp by adding QSA. Supercool!
