### ISSUE TITLE
Add subdomain redirects for easy language switching 

### ISSUE THREAD

**Issue by rootfather** [scummvm/scummvm-web#36]
I recommend adding a number of subdomain to make linking to a specific language version of the ScummVM website or to a specific translation of a news article easier.

As an example, de.scummvm.org should redirect to the URL ?lang=de, ru.scummvm.org to ?lang=ru... you get the idea.

**Comment by sev-** [comment]
Could you please elaborate a tiny bit, why it is easier than adding ?lang=de ?

**Comment by rootfather** [comment]
Maybe I am thinking way too complicated, but it think it would make it easier to link to a specific page. Maybe it would also simplify the whole language-switching thing - instead of relying on a cookie, the language could be selected by the subdomain itself.

Example:
The direct URL of the 1.8.0 release announcement is http://scummvm.org/news/20160304/.
The language of this news is selected via the Cookie set by the ?lang= parameter. When I give the direct link to the news to somebody, I have to use http://scummvm.org/news/20160304/?lang=de. Due to the current flaws of the language selector, the user has to refresh the page once in order to get the translated version. I'm also not sure if the language selector works in environments/browser setups where cookies and/or scripts are not allowed.

Instead, I propose that the language is not set by a cookie, but by the subdomain instead.

When I visit:
http://de.scummvm.org/news/20160304/ I get the German translation,
http://ru.scummvm.org/news/20160304/ I get the Russian version and so on - regardless what's selected by the language selector.

Therefore I propose specific subdomains for the translations. When I visit de.scummvm.org I get the German revision of the website where ru.scummvm.org takes me to the Russian one and scummvm.org to the default english version.

If you need an example, check out the website of libreoffice.org - they use the country codes as subdomains for the specific local versions of their website too.

**Comment by sev-** [comment]
Now, after @wjp has fixed the redirects, you can use `?lang=de` suffixes without restrictions. Thus, this feature request is not needed.
