### ISSUE TITLE
Language menu not visible on iOS and Android

### ISSUE THREAD

**Issue by criezy** [scummvm/scummvm-web#52]
Today SimSaw told me he could not see the language menu on his android phone while he could in the past. I don't have an android device to check, but I checked on my iPad and I have the same issue.

Using the WebInspector to highlight it I could determine that the language menu is not at the correct location: it is around the Forums links on the main menu (but is not visible):

![webinspector_mobilesafari](https://cloud.githubusercontent.com/assets/552105/14618261/a3b24942-05a9-11e6-8192-a371c8ba49a0.png)

**Comment by criezy** [comment]
The same happens in Safari, Chrome and Firefox desktop if I reduce the width of the window sufficiently.

**Comment by salty-horse** [comment]
That's a regression from my recent changes. :(
I'll fix it in a few days.
