### ISSUE TITLE
Issue with text alignment in the intro boxes

### ISSUE THREAD

**Issue by criezy** [scummvm/scummvm-web#56]
In the intro box of the download page, with the navigation on the left and intro text on the right, there is an issue with the text alignment if it is higher than the navigation box. This happens when there is more than 12 lines of intro text. Starting with the 13th line, additional line start slightly more to the left. This is mostly visible with the French and German translations that have more text, but can be seen with the English text when reducing sufficiently the width of the page. See for example the image below.

![intro_text_align](https://cloud.githubusercontent.com/assets/552105/15053873/9ae720a2-12fc-11e6-9068-99fa82b5b08d.png)

**Comment by rootfather** [comment]
Should be fixed with 032d81562f5dde3b877e15fca341d0a5ab5ad689.

**Comment by criezy** [comment]
This looks OK now (tested with Safari, Chrome and Firefox).
Thank you.
