### ISSUE TITLE
Unusable garbage on Chromium 66

### ISSUE THREAD

**Issue by hamakei** [scummvm/scummvm-web#80]
Looks like some badly formatted mobile site from 2003.

![untitled](https://user-images.githubusercontent.com/30203431/42138398-e870762c-7d74-11e8-8651-3113d5a053d5.png)

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36

**Comment by hamakei** [comment]
Makes no difference. Even browsing in private mode (with no cache or cookies) it looks like that.

**Comment by tsoliman** [comment]
Tested with Chromium 67 on Linux (Debian 9 64bit) and it works fine.
(Fresh install in a VM)

**Comment by tsoliman** [comment]
@hamakei is an extension blocking something?
Are there any errors in the JS console? (ctrl-shift-j)
Any non-200s in the Network tab?

**Comment by hamakei** [comment]
Ah. There is a javascript error...
"Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" - pixel.gif from paypalobjects.com

**Comment by Mataniko** [comment]
@hamakei I've tried to reproduce using Chromium 66 on Ubuntu with uBlock Origin. 

I see pixel.gif being blocked, but the rest of the site loads fine. Do you have any other addons installed that might be interfering? Any other information from the console that you can share?

**Comment by metakid** [comment]
I see the same thing on android, on a samsung S6 in chrome. The responsive is not responding. It does sort of make you feel like you were pulled into the past by some kind of space vortex thing. Which I guess is sort of the point of this project. :|

**Comment by Mataniko** [comment]
Can you consistently reproduce? It feels like you're getting a cached version. 

If possible, use Chrome remote debugger to capture a network log and send

**Comment by bonki** [comment]
I can't reproduce this either. Tested with Chromium 37, Chrome 65 and 67 on Windows, Linux and Android and different versions of uBlock Origin.
