### ISSUE TITLE
AMIGAOS: "Scumm"VM logo appears black

### ISSUE THREAD

**Issue by raziel-** [scummvm/scummvm-web#82]
The ScummVM logo on the top left of the main homepage appears black for me.
https://s33.postimg.cc/xf91ckd7z/Workbench_Screen_016.png

**Comment by Mataniko** [comment]
There were a bunch of rendering issues with the texture in the SVG version of the logo. Moving to the rasterized version until someone redoes the vector logo.

Fixed in  e391b73.
