### ISSUE TITLE
RSS/Atom Feeds for planet.scummvm missing

### ISSUE THREAD

**Issue by Diskutant** [scummvm/scummvm-web#83]
Since the Website got updated the url for the feed changed, and now it shows only the entries from the main page, but not for planet.scummvm.org

**Comment by Mataniko** [comment]
The new update hasn't touched the feeds at all, or planet.scummvm.org. 

I think planet always had its own feed at: http://planet.scummvm.org/rss20.xml which included both site news and planet.

**Comment by Diskutant** [comment]
I had the feed at https://www.scummvm.org/atom.xml in my feed reader, it contained news from planet.scummvm.org. Now that one gets a 404. 

Your link seems to work, thanks. Is it linked anywhere though? I wasn't able to find it on the page.

**Comment by Mataniko** [comment]
Hmmm, looking at the history www.scummvm.org/feeds/atom has been the URL for the past two years. I've set up a copy of the site here for sanity checks: https://scummvm-old.herokuapp.com

The planet feed is here: http://planet.scummvm.org/

**Comment by Diskutant** [comment]
> The planet feed is here: http://planet.scummvm.org/

Yes, I was searching the link to the feed on that side. Found it now in the sidebar under Subscription Links, I searched the page (cmd+f) for 'rss' and 'feed' before and couldn't find it.
