### ISSUE TITLE
Page Format issue on safari 11.1.1

### ISSUE THREAD

**Issue by vincione** [scummvm/scummvm-web#86]
[ScummVM : Home.pdf](https://github.com/scummvm/scummvm-web/files/2183409/ScummVM.Home.pdf)

Hello,
I sent you a PDF file on the issue i get on my MacBook Pro 8,2 1440x900 on high Sierra Safari 11.1.1.
I don't have this issue on Chrome.

**Comment by Mataniko** [comment]
Can you please export the network data from Safari developer tools?

Enable Developer tools in Preferences -> Advanced and then toggle it on from the Develop menu. Go to the Network tab, refresh the page and click export in the top right corner of the tools window.

**Comment by vincione** [comment]
I found the fix.

In the develop menu i cleared the cache and everything is fine now.

It has been something to do with the previous website in cache.
